### ISSUE TITLE
SSL证书和自签名证书

### ISSUE THREAD

**Issue by Liqiankun** [fusugz/YMHttpsTest#3]
请问这两个证书是怎么生成的？

**Comment by songminzh** [comment]
SSL证书是与服务器安装的证书一致的CA文件，需要根证书，以便针对所有相关域名的验证；自签名的证书是通过后台生成的，直接让后台生成一个自签名CA，当然正式环境中需要和服务器证书一致。

**Comment by Liqiankun** [comment]
所以SSL文件是本地的对吧！

**Comment by songminzh** [comment]
对，需要打包到本地，其实SSL证书可以不打包到本地直接用系统方法实现证书验证，请查看README.md中的系统方法。

**Comment by Liqiankun** [comment]
对这块不是很了解，多问一下。`NSString *cerPath = [[NSBundle mainBundle] pathForResource:certificate ofType:@"cer"];`中的`certificate`是SSL的证书吗？

**Comment by songminzh** [comment]
对的，就是Bundle中证书的名称

**Comment by Liqiankun** [comment]
我用的这个`openssl s_client -connect www.google.com:443 </dev/null 2>/dev/null | openssl x509 -outform DER > https.cer`生成的。现在是不是对了？

**Comment by Liqiankun** [comment]
不好意思打扰你了，但是还有些资料说如果是SSL商用的客户端除了把http改成https其他什么都不需要这个和你的用AFNetworking方法有区别吗？

**Comment by songminzh** [comment]
是的，当时和后台测试的时候也是用openssl生成的，测试可以通过。iOS官方已经支持了https，只要是服务端用的是SSL证书，直接用官方的网络方法就可以直接进行https访问，区别就是AFNetworking必须要将SSL证书打包到本地进行证书验证，而系统方法只要你的SSL证书颁发机构在我README.md中提到的苹果官方清单内，就可以直接进行https访问。另外，在我的尝试中，如果直接用AFNetworking的方法却不能访问https的接口，不知道原因是什么，也许是作者目前还没有支持或者是我这边处理有问题。

**Comment by Liqiankun** [comment]
非常感谢！谢谢你耐心的解答。

**Comment by songminzh** [comment]
我还有很多不懂，目前做这方面的不多，我也是看了很多国外开发者的回答和官方的一些说明才做了初步的总结，可能还有许多地方需要根据官方的要求进一步调整，一起学习－－
